### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by efremidze** [mathcarignani/MCMHeaderAnimated#2]
I made a swift-2.0 branch with swift 2.0 support
https://github.com/efremidze/MCMHeaderAnimated/tree/swift-2.0

**Comment by efremidze** [comment]
https://github.com/efremidze/MCMHeaderAnimated/tree/swift-2.0

**Comment by mathcarignani** [comment]
@efremidze thanks! and sorry for the long delay
